name: redtown
description: RedTown Reddit Media Scraper
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.2.1
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
